### ISSUE TITLE
Error on `GuiFont Consolas:h09`

### ISSUE THREAD

**Issue by bohrshaw** [equalsraf/neovim-gui-shim#1]
The above command reports: `Warning: Font "Consolas" reports bad fixed pitch metrics`.

OS: Windows 10 32bit

**Comment by equalsraf** [comment]
@BohrShaw the error is specific to nvim-qt the shim itself does nothing about font metrics.

What is happening is that (for some reason) Qt considers that the font you have loaded does not appear to be a monospace font and as such might not look correct. For some reason this is more common in Windows, but its not a fatal error.

**Comment by bohrshaw** [comment]
Thanks for your explanation.

**Comment by gaving** [comment]
I'm just curious if there was any way to suppress this (or convince Qt it's fine)?

Been getting this daily for years now and while it's harmless it still is an enter press on launch to get past it. Using Consolas here too.

**Comment by bohrshaw** [comment]
@gaving `GuiFont! Consolas:h10`(Notice the `!`) should suppress the error.

**Comment by gaving** [comment]
@bohrshaw Doh, that seems sort of obvious. Thanks!

**Comment by ghost** [comment]
@bohrshaw Thanks for your tips. Now can get rid of this warning
