### ISSUE TITLE
Is this plugin still being maintained?

### ISSUE THREAD

**Issue by Kraust** [equalsraf/neovim-gui-shim#6]
When looking into Ligature support I noticed that this plugin differs greatly to https://github.com/equalsraf/neovim-qt/blob/master/src/gui/runtime/plugin/nvim_gui_shim.vim. As I use neovim-qt primarily for remote attachment, it doesn't look like these newer features are available to me, as they're only maintained in the non-shim version. Using the shim actually removes the newer features if the plugin is enabled locally.

**Comment by equalsraf** [comment]
Thanks @Kraust I have merged the changes.
